name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          python -m grpc_tools.protoc -I. --python_out=src --grpc_python_out=src src/text2image.proto
      - name: Build Docker image
        run: docker build -t text2image:latest .
      - name: Run container tests
        run: docker run text2image pytest tests/unit
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag and push to Docker Hub
        run: |
          docker tag text2image:latest your-dockerhub-username/text2image:latest
          docker tag text2image:latest your-dockerhub-username/text2image:${{ github.sha }}
          docker push your-dockerhub-username/text2image:latest
          docker push your-dockerhub-username/text2image:${{ github.sha }}